### ISSUE TITLE
first install issue

### ISSUE THREAD

**Issue by m0yellow** [alerta/alerta-docs#73]
I'm trying to get a first install to life.
It is more a tenth install now, so I make an issue out of it, since it should be working according to the documentation.

Install: opensuse tumbleweed VM (minimal+plus required packages listed)

I tried installing from github master,
I did follow the install.sh for debian (adapted)

I disabled auth, but on the angular-web-ui I get login / signup, and signup fails.
when I try alerta on the cli, I get various errors:

     alerta query --filters text=~disk
     Error: no such option: --filters

on other commands I get unexplained json errors (see below).
I do have a running alertad process, and I have deployed and modified flask apps in the past, so I think my basic setup should be acceptable, at least enough to produce speaking errors. 

```
alerta top
Traceback (most recent call last):
  File "/usr/bin/alerta", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/alertaclient/commands/cmd_top.py", line 15, in cli
    screen.run()
  File "/usr/lib/python3.6/site-packages/alertaclient/top.py", line 26, in run
    wrapper(self.main)
  File "/usr/lib64/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3.6/site-packages/alertaclient/top.py", line 69, in main
    self.update()
  File "/usr/lib/python3.6/site-packages/alertaclient/top.py", line 83, in update
    status = self.client.mgmt_status()
  File "/usr/lib/python3.6/site-packages/alertaclient/api.py", line 276, in mgmt_status
    return self.http.get('/management/status')
  File "/usr/lib/python3.6/site-packages/alertaclient/api.py", line 324, in get
    return self._handle_error(response)
  File "/usr/lib/python3.6/site-packages/alertaclient/api.py", line 356, in _handle_error
    resp = response.json()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
    ps ax | grep /alerta
    12553 pts/0    S      0:00 /usr/bin/python3 /usr/bin/alertad run

**Comment by satterly** [comment]
I haven't tested `install.sh` in a while so wouldn't be surprised if it's broken. Can you share your `api.wsgi` file? I'd bet it's wrong. It should be something like ...
```
#!/usr/bin/env python
activate_this = '/opt/alerta/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))
from alerta import app as application
```
https://github.com/alerta/alerta/blob/master/contrib/apache/api.wsgi

**Comment by satterly** [comment]
Please also share the changes you made to `install.sh` as it's difficult (impossible) for me to try reproduce the problem you are experiencing without knowing what commands you ran. Thanks!

**Comment by satterly** [comment]
I got this working on openSUSE after making significant changes to the `install.sh` script. See https://github.com/alerta/vagrant-try-alerta/blob/master/scripts/opensuse/alerta.sh
